version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8282:8282"
    volumes:
      - .:/app
    environment:
      COMPOSER_ALLOW_SUPERUSER: '1'
    command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8282"]
    depends_on:
      - db
    networks:
      - laravel-network 
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'laravel1'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3307:3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - laravel-network  

volumes:
  my-db:

networks:
  laravel-network:  
